version: "2"

volumes:
  redis_data:
    driver: local

services:
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  worker:
    container_name: worker
    hostname: worker
    restart: unless-stopped
    build:
      context: .
    image: pylineup:1
    volumes:
      - ./:/pylineup
    command:
      [
        "celery",
        "--app=pylineup",
        "worker",
        "--hostname=jobs@worker",
        "--loglevel=INFO",
        "--pidfile=/tmp/celeryworker.pid",
      ]
    depends_on:
      - redis
    stdin_open: true
    tty: true

  beat:
    container_name: beat
    hostname: beat
    restart: unless-stopped
    image: pylineup:1
    volumes:
      - ./:/pylineup
    command:
      [
        "celery",
        "--app=pylineup",
        "beat",
        "--pidfile=/tmp/celerybeat.pid",
        "--loglevel=INFO",
      ]
    depends_on:
      - worker
      - redis
    stdin_open: true
    tty: true

  flower:
    container_name: flower
    hostname: flower
    restart: unless-stopped
    image: pylineup:1
    volumes:
      - ./:/pylineup
    command:
      [
        "celery",
        "--app=pylineup",
        "flower",
        "--port=8080",
        "--broker=redis://redis:6379/0",
        "--broker_api=redis://redis:6379/0",
        "--basic_auth=admin:admin",
      ]
    ports:
      - 80:8080
    depends_on:
      - worker
      - beat
      - redis
